# print("Мы изучаем язык Python")
# print("Python")
# print("Python")
# print("Скоро я", "буду программировать", "на языке", "Python!", sep="-")
# print('Какой хороший день!')
# print('Работать мне не лень!')
# print('Какой хороший день!')
# print()
# print('Работать мне не лень!')
# print('В тексте есть "двойные" кавычки')
# print("В тексте есть 'одинарные' кавычки")
# print(4, 8, 15, 16, 23, 42, sep='\n')
# print('*', '**', '***', '****', '*****', '******', '*******', sep='\n')
# print('Как тебя зовут?')
# name = input()
# print('Привет,', name)
# # сначала тут печатается строка "Как тебя зовут", а потом принимается на вход имя
# name = input('Как тебя зовут?'+'\n')
#
# # тут просто выводится строка "Привет", после неё идёт пробел и введённое нами имя
# print('Привет,', name)
# n = input()
# print('Привет,', input())
# print(input(), '- чемпион!')
# print(input(), input(), input(), sep='\n')
# a = input()
# b = input()
# c = input()
# print(c, b, a, sep='\n')
# print(*reversed([input(), input(), input()]), sep="\n")
# a, b, c = input(), input(), input()
# print(c, b, a, sep="\n")
# print('a', 'b', 'c', end='@')
# print('d', 'e', 'f', end='@@')
# print('a', 'b', 'c', sep='*', end='finish')
# print('d', 'e', 'f', sep='**', end='^__^')
# print('g', 'h', 'i', sep='+', end='%')
# print('j', 'k', 'l', sep='-', end='#')
# print('m', 'n', 'o', sep='/', end='!')
# print('31', '12', '2019', sep='-')
# print('Mercury', 'Venus', sep='*', end='!')
# print('Mars', 'Jupiter', sep='**', end='?')
# print('a', 'b', 'c', sep='*')
# print('d', 'e', 'f', sep='**', end='')
# print('g', 'h', 'i', sep='+', end='%')
# print('j', 'k', 'l', sep='-', end='\n')
# print('m', 'n', 'o', sep='/', end='!')
# print('p', 'q', 'r', sep='1', end='%')
# print('s', 't', 'u', sep='&', end='\n')
# print('v', 'w', 'x', sep='%')
# print('y', 'z', sep='/', end='!')
# print('I***like***Python')
# a = input()
# print(input(), input(), input(), sep=a)
# print('Привет, ', input(), '!', sep='')
# variable_name = input()
# print('Вы ввели текст:', variable_name)
# print('Как тебя зовут?')
# name = input()
# print('Привет,', name)
# name = 'Timur'
# print('Привет,', name)
name, surname = 'Timur', 'Guev'
print('Имя:', name, 'Фамилия:', surname)